### ISSUE TITLE
My site won't go online

### ISSUE THREAD

**Issue by natduboiss** [natduboiss/html-validation-fixes#1]
I did all the coding and everything is good however when I drop the file in Markbot it tells me my site isn't online. However when I check GitHub to see if it's online they say that it is. I've updated Markbot to the new version as well.

@thomasjbradley

**Comment by thomasjbradley** [comment]
If you go to the repo page on GitHub.com you'll see that the `Index.html` is misspelled. I know you fixed it on your computer, but MacOS will not detect filename changes from upper to lower case.

To fix you'll have to:

1. On your computer: completely rename index to something different like `dino.html`
2. Commit this change in the GitHub app.
3. Rename it back to `index.html`
4. Commit this change in the GitHub app.

Then it should work within a few minutes.

**Comment by natduboiss** [comment]
@thomasjbradley thank you it worked!
